spring:
  application:
    name: meetup2024
  datasource:
    hikari:
      schema: myschema
      maximum-pool-size: 2
      pool-name: pg-myschema
  flyway:
    default-schema: myschema
    clean-on-validation-error: true # dev only
    clean-disabled: false # dev only
  jackson:
    deserialization:
      fail-on-unknown-properties: false
